// Code generated by protoc-gen-go.
// source: index.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	index.proto

It has these top-level messages:
	IndexEntry
	Index
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexEntry struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Suite     string `protobuf:"bytes,2,opt,name=suite" json:"suite,omitempty"`
	Binarypkg string `protobuf:"bytes,3,opt,name=binarypkg" json:"binarypkg,omitempty"`
	Section   string `protobuf:"bytes,4,opt,name=section" json:"section,omitempty"`
	Language  string `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
}

func (m *IndexEntry) Reset()                    { *m = IndexEntry{} }
func (m *IndexEntry) String() string            { return proto1.CompactTextString(m) }
func (*IndexEntry) ProtoMessage()               {}
func (*IndexEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IndexEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndexEntry) GetSuite() string {
	if m != nil {
		return m.Suite
	}
	return ""
}

func (m *IndexEntry) GetBinarypkg() string {
	if m != nil {
		return m.Binarypkg
	}
	return ""
}

func (m *IndexEntry) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *IndexEntry) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type Index struct {
	Entry    []*IndexEntry     `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	Language []string          `protobuf:"bytes,2,rep,name=language" json:"language,omitempty"`
	Suite    map[string]string `protobuf:"bytes,3,rep,name=suite" json:"suite,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Section  []string          `protobuf:"bytes,4,rep,name=section" json:"section,omitempty"`
}

func (m *Index) Reset()                    { *m = Index{} }
func (m *Index) String() string            { return proto1.CompactTextString(m) }
func (*Index) ProtoMessage()               {}
func (*Index) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Index) GetEntry() []*IndexEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Index) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Index) GetSuite() map[string]string {
	if m != nil {
		return m.Suite
	}
	return nil
}

func (m *Index) GetSection() []string {
	if m != nil {
		return m.Section
	}
	return nil
}

func init() {
	proto1.RegisterType((*IndexEntry)(nil), "proto.IndexEntry")
	proto1.RegisterType((*Index)(nil), "proto.Index")
}

func init() { proto1.RegisterFile("index.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0xe5, 0x78, 0x0d, 0xec, 0x6c, 0x03, 0x23, 0x24, 0xac, 0x15, 0x45, 0xb4, 0x0d, 0xdb,
	0x90, 0x02, 0x9a, 0x88, 0x9e, 0x82, 0x36, 0x9c, 0xc0, 0x01, 0x2b, 0xb2, 0x12, 0x9c, 0x28, 0x71,
	0x10, 0xb9, 0x02, 0x97, 0xe3, 0x4a, 0xc8, 0xe3, 0xfc, 0x56, 0x9e, 0x37, 0xcf, 0x7a, 0xfe, 0xfc,
	0xe0, 0x60, 0xec, 0xa7, 0xfe, 0x49, 0x9a, 0xb6, 0x76, 0x35, 0x0a, 0x3a, 0x4e, 0xbf, 0x0c, 0xe0,
	0xcd, 0xaf, 0x5f, 0xad, 0x6b, 0x07, 0x44, 0xd8, 0x59, 0xf5, 0xa5, 0x25, 0x8b, 0xd9, 0x79, 0x9f,
	0xd1, 0x8c, 0xb7, 0x20, 0xba, 0xde, 0x38, 0x2d, 0x23, 0x5a, 0x06, 0x81, 0xf7, 0xb0, 0xcf, 0x8d,
	0x55, 0xed, 0xd0, 0x94, 0x85, 0xe4, 0xe4, 0x2c, 0x0b, 0x94, 0x70, 0xd9, 0xe9, 0x0f, 0x67, 0x6a,
	0x2b, 0x77, 0xe4, 0x4d, 0x12, 0x8f, 0x70, 0x55, 0x29, 0x5b, 0xf4, 0xaa, 0xd0, 0x52, 0x90, 0x35,
	0xeb, 0xd3, 0x1f, 0x03, 0x41, 0x30, 0xf8, 0x00, 0x42, 0x7b, 0x20, 0xc9, 0x62, 0x7e, 0x3e, 0x3c,
	0xdd, 0x04, 0xe8, 0x64, 0x21, 0xcd, 0x82, 0xbf, 0x89, 0x8b, 0x62, 0xbe, 0x8e, 0xc3, 0xc7, 0x09,
	0x9c, 0x53, 0xc8, 0xdd, 0x3a, 0x24, 0x79, 0xf7, 0xce, 0x18, 0x15, 0x7e, 0xb4, 0x61, 0xe6, 0x2b,
	0xe6, 0x63, 0x0a, 0xb0, 0x5c, 0xc7, 0x6b, 0xe0, 0xa5, 0x1e, 0xc6, 0x8a, 0xfc, 0xe8, 0x1b, 0xfa,
	0x56, 0x55, 0x3f, 0x37, 0x44, 0xe2, 0x25, 0x4a, 0x59, 0x7e, 0x41, 0x4f, 0x3e, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0xe5, 0x32, 0xf9, 0x7b, 0x01, 0x00, 0x00,
}
