.TH REFS 1 "2016-12-23" "debiman"
.SH NAME
refs \- test file

.SH SEE ALSO
.\" Using .UR results in a <a> element (most convenient to work with).
.UR http://w3m.sourceforge.net
project website
.UE

More details can be found in the i3lock(1) or refs(1) man pages.

References to i3-msg(1) might cause trouble when matching on word boundaries.

References to systemd.service(5) contain a dot.

URLs in plain text, like http://debian.org are also recognized and converted.

Marked up URLs like \fIhttp://gnome.org\fP are also converted.
